mod.name=BehindYouV3
mod.id=behindyouv3
mod.version=3.4.2
mod.group=org.polyfrost

loomx.loom_version=1.17-SNAPSHOT
loader_version=0.19.2
oneconfig_version=1.0.0-beta.7
minecraft_version=[VERSIONED]
parchment_version=[VERSIONED]
yalmm_version=[VERSIONED]

publish.modrinth=sAFPANmp

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.parallel.threads=4
org.gradle.jvmargs=-Xmx4G

# Fix YALMM
fabric.loom.dropNonIntermediateRootMethods=true
