mod.name=BehindYouV3
mod.id=behindyouv3
mod.version=3.3.0-alpha.2
mod.group=org.polyfrost

loom_version=1.14-SNAPSHOT
loader_version=0.18.4
oneconfig_version=1.0.0-alpha.182
parchment_version=[VERSIONED]
yalmm_version=[VERSIONED]

publish.modrinth=sAFPANmp

org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureoncommand=true
org.gradle.parallel.threads=4
org.gradle.jvmargs=-Xmx2G

# Fix YALMM
fabric.loom.dropNonIntermediateRootMethods=true