kotlin.code.style=official

mod.version=3.3.0-alpha.2
mod.id=behindyouv3
mod.name=BehindYouV3
mod.group=org.polyfrost

# Gradle Configuration -- DO NOT TOUCH THESE VALUES.
polyfrost.defaults.loom=3
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureoncommand=true
org.gradle.parallel.threads=4
org.gradle.jvmargs=-Xmx2G
loom.ignoreDependencyLoomVersionValidation=true
